### ISSUE TITLE
Add REPL functionality

### ISSUE THREAD

**Issue by decentral1se** [core-api/coreapi-cli#20]
Would you be willing to accept a PR that integrates with https://github.com/click-contrib/click-repl/? I've played around with it and it definitely improves the experience of navigating schemas.

Without anything beyond the following diff,

``` diff
diff --git a/coreapi_cli/main.py b/coreapi_cli/main.py
index 8537187..1c084a4 100644
--- a/coreapi_cli/main.py
+++ b/coreapi_cli/main.py
@@ -5,6 +5,7 @@ from coreapi_cli.display import display
 from coreapi_cli.debug import DebugSession
 from coreapi_cli.history import History, dump_history, load_history
 import click
+import click_repl
 import coreapi
 import json
 import os
@@ -741,6 +742,7 @@ history.add_command(history_show, name='show')
 client.add_command(codecs)
 codecs.add_command(codecs_show, name='show')
 
+click_repl.register_repl(client)
 
 if __name__ == '__main__':
     client()
```

It's looking nice:

![get-complete](https://user-images.githubusercontent.com/1991377/27765939-03653026-5eb8-11e7-965c-4afb4d07a4ff.png)

![opt-complete](https://user-images.githubusercontent.com/1991377/27765940-047f2c5a-5eb8-11e7-90cf-34ff0eb7a03a.png)

I'd try to add some more features there - colors, fuzzy finder, history, etc.

**Comment by lovelydinosaur** [comment]
That's really neat! I think I'll keep that out of the scope of this project, since I don't want to have to maintain support for it. Perhaps a neat idea for a stand alone tool that only uses the repl?
