### ISSUE TITLE
coreapi-cli randomly connects to the wrong port

### ISSUE THREAD

**Issue by ksze** [core-api/coreapi-cli#24]
I was trying to follow the Django REST Framework tutorial. In [part 7 of the tutorial](http://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/), we're told to use coreapi-cli to inspect and test the REST API.

Besides the fact that I'm affected by #19, I have also run into a weird issue where, after running the `coreapi` command a few times, it would "randomly" try to connect to my test server on port 80 instead of the port 8001 (which is the port my test server is running on). I have not yet noticed a pattern of *how* this happens, however.

**Comment by blueyed** [comment]
Reminded me of https://github.com/core-api/coreapi-cli/pull/22.

**Comment by lovelydinosaur** [comment]
@blueyed Yup - could well be something like redirects on --debug being effected.
I'll close this since #26 and the 1.0.8 release may well be the fix.
Welcome to reopen if an issue persists.
